### ISSUE TITLE
Alarm Server close connection and not responding

### ISSUE THREAD

**Issue by mistermax80** [mistermax80/ialarm_mk2#3]
2024-11-21 01:20:08.485 - Start Home Assistant
2024-11-22 18:49:44.982 - First critical error

After 2 days the server closes connection and it's not responnde.

Log:
`2024-11-22 18:49:44.982 DEBUG (MainThread) [custom_components.ialarm_mk2.coordinator] Finished fetching ialarm_mk2 data in 0.745 seconds (success: True)
2024-11-22 18:49:52.068 DEBUG (MainThread) [custom_components.ialarm_mk2.hub] Numbers of threads for'iAlarmMK2-ThreadID': 1
2024-11-22 18:49:52.068 DEBUG (MainThread) [custom_components.ialarm_mk2.hub] Active thread: iAlarmMK2-ThreadID-214
2024-11-22 18:50:24.744 DEBUG (iAlarmMK2-ThreadID-214) [custom_components.ialarm_mk2.hub] iAlarmMkPushClient - _keepalive, sent messagge:b'%maI'
2024-11-22 18:50:24.779 DEBUG (MainThread) [custom_components.ialarm_mk2.hub] iAlarmMkPushClient - handle_read - Header: b'%maI', Data Length: 4
2024-11-22 18:50:24.779 DEBUG (MainThread) [custom_components.ialarm_mk2.hub] iAlarmMkPushClient - handle_read - Keepalive message received.
2024-11-22 18:50:44.238 INFO (MainThread) [custom_components.ialarm_mk2.coordinator] Fetching data...
2024-11-22 18:50:44.241 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Updating internal state: DISARMED(1)
2024-11-22 18:50:44.242 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Login method called.
2024-11-22 18:50:44.243 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Checking if the socket is already connected.
2024-11-22 18:50:44.243 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket file descriptor:36.
2024-11-22 18:50:44.244 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket already connected.
2024-11-22 18:50:44.245 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Login ok.
2024-11-22 18:50:44.414 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 357
2024-11-22 18:50:44.566 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 358
2024-11-22 18:50:44.707 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 358
2024-11-22 18:50:44.749 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 0
2024-11-22 18:50:44.750 ERROR (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Error during fetch data.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 174, in _update_data
    status = self.hub.ialarmmk.ialarmmkClient.GetByWay()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 174, in GetByWay
    return self._(xpath, cmd, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 730, in _
    self._(xpath, cmd, is_list, offset, l)
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 730, in _
    self._(xpath, cmd, is_list, offset, l)
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 730, in _
    self._(xpath, cmd, is_list, offset, l)
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 717, in _
    resp = self._receive()
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 756, in _receive
    return xmltodict.parse(
           ^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/xmltodict.py", line 359, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
2024-11-22 18:50:44.921 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Logout method called.
2024-11-22 18:50:44.922 INFO (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] After error, logout ok.
2024-11-22 18:50:44.923 INFO (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Retrying... Attempt 2 of 3 in 1 seconds.
2024-11-22 18:50:44.923 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Waiting 1 second before next attempt.
2024-11-22 18:50:45.924 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Finished waiting, retrying now.
2024-11-22 18:50:45.925 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Login method called.
2024-11-22 18:50:45.925 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Invalid or uninitialized socket, creating a new socket.
2024-11-22 18:50:45.925 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Checking if the socket is already connected.
2024-11-22 18:50:45.926 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket file descriptor:35.
2024-11-22 18:50:45.926 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket is not connected, error messagge: [Errno 107] Transport endpoint is not connected. Proceding to close old socket.
2024-11-22 18:50:45.927 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Re-initialized new socket, creating a new socket.
2024-11-22 18:50:45.932 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket not connected, setting timeout and attempting to connect.
2024-11-22 18:50:45.933 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Attempting to connect to the server.
2024-11-22 18:50:45.967 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Connection successful, proceeding with login to server.
2024-11-22 18:50:46.007 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 0
2024-11-22 18:50:46.008 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Unexpected error during login: no element found: line 1, column 0
2024-11-22 18:50:46.010 ERROR (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Error during fetch data.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 114, in login
    self.client = self._(xpath, cmd)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 717, in _
    resp = self._receive()
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 756, in _receive
    return xmltodict.parse(
           ^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/xmltodict.py", line 359, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 172, in _update_data
    self.hub.ialarmmk.ialarmmkClient.login()
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 140, in login
    raise ClientError("Unexpected error during login")
custom_components.ialarm_mk2.libpyialarmmk.pyialarmmk.ClientError: Unexpected error during login
2024-11-22 18:50:46.022 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Logout method called.
2024-11-22 18:50:46.023 INFO (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] After error, logout ok.
2024-11-22 18:50:46.023 INFO (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Retrying... Attempt 3 of 3 in 1 seconds.
2024-11-22 18:50:46.023 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Waiting 1 second before next attempt.
2024-11-22 18:50:47.024 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Finished waiting, retrying now.
2024-11-22 18:50:47.025 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Login method called.
2024-11-22 18:50:47.025 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Invalid or uninitialized socket, creating a new socket.
2024-11-22 18:50:47.027 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Checking if the socket is already connected.
2024-11-22 18:50:47.028 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket file descriptor:29.
2024-11-22 18:50:47.029 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket is not connected, error messagge: [Errno 107] Transport endpoint is not connected. Proceding to close old socket.
2024-11-22 18:50:47.030 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Re-initialized new socket, creating a new socket.
2024-11-22 18:50:47.030 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Socket not connected, setting timeout and attempting to connect.
2024-11-22 18:50:47.031 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Attempting to connect to the server.
2024-11-22 18:50:47.063 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Connection successful, proceeding with login to server.
2024-11-22 18:50:47.100 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Data received is length: 0
2024-11-22 18:50:47.101 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Unexpected error during login: no element found: line 1, column 0
2024-11-22 18:50:47.104 ERROR (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Error during fetch data.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 114, in login
    self.client = self._(xpath, cmd)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 717, in _
    resp = self._receive()
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 756, in _receive
    return xmltodict.parse(
           ^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/xmltodict.py", line 359, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 172, in _update_data
    self.hub.ialarmmk.ialarmmkClient.login()
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 140, in login
    raise ClientError("Unexpected error during login")
custom_components.ialarm_mk2.libpyialarmmk.pyialarmmk.ClientError: Unexpected error during login
2024-11-22 18:50:47.114 DEBUG (SyncWorker_7) [custom_components.ialarm_mk2.hub] Logout method called.
2024-11-22 18:50:47.115 INFO (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] After error, logout ok.
2024-11-22 18:50:47.115 ERROR (SyncWorker_7) [custom_components.ialarm_mk2.coordinator] Failed after 3 attempts
2024-11-22 18:50:47.117 ERROR (MainThread) [custom_components.ialarm_mk2.coordinator] Error during fetch data.
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 114, in login
    self.client = self._(xpath, cmd)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 717, in _
    resp = self._receive()
           ^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 756, in _receive
    return xmltodict.parse(
           ^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.12/site-packages/xmltodict.py", line 359, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 172, in _update_data
    self.hub.ialarmmk.ialarmmkClient.login()
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/libpyialarmmk/pyialarmmk.py", line 140, in login
    raise ClientError("Unexpected error during login")
custom_components.ialarm_mk2.libpyialarmmk.pyialarmmk.ClientError: Unexpected error during login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 151, in _async_update_data
    await self.hass.async_add_executor_job(self._update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/ialarm_mk2/coordinator.py", line 185, in _update_data
    raise UpdateFailed(e) from e
homeassistant.helpers.update_coordinator.UpdateFailed: Unexpected error during login
2024-11-22 18:50:47.184 ERROR (MainThread) [custom_components.ialarm_mk2.coordinator] Error fetching ialarm_mk2 data: Unexpected error during login
2024-11-22 18:50:47.184 DEBUG (MainThread) [custom_components.ialarm_mk2.coordinator] Finished fetching ialarm_mk2 data in 2.947 seconds (success: False)`

**Comment by diebra** [comment]
Hi, same problem for me. With an integration reload it became operational, so it may be necessary to provide a scheduled refresh of the connection token (if present) or try to log in again. 

I hope my opinion can be useful.

**Comment by mistermax80** [comment]
Yes, I'm currently testing this. I plan to force token regeneration after a specific period of time.
On my server, I’ve set up an automation to reload when sensors become "unavailable", but in this scenario, some threads remain active, causing the same notification to be received multiple times.

My automation:
`alias: Auto - Notifica - Allarme non disponibile - riavvia integrazione
description: ""
triggers:
  - trigger: state
    entity_id:
      - alarm_control_panel.ialarm_mk
    from: null
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
conditions: []
actions:
  - action: homeassistant.reload_config_entry
    target:
      device_id: 429ef4ac9e9fb0f9502e5423714689a5
    data: {}
  - action: notify.notifica_per_massimo
    metadata: {}
    data:
      message: Allarme connessione non disponibile, riavviata l'integrazione.
      title: Allarme connessione non disponibile
mode: single`

**Comment by mistermax80** [comment]
> Hi, same problem for me. With an integration reload it became operational, so it may be necessary to provide a scheduled refresh of the connection token (if present) or try to log in again.
> 
> I hope my opinion can be useful.

I tried to do that you advice, but it doesn't work, after 2 days integration gone unavailable.

Any idea to reload objects at level code?

**Comment by alexvan** [comment]
Il device_id dove si trova?
